/**
 * Golfbert API
 * This API allows you to access rich golf course information, including gps coordinates and geo polygons of courses holes. This API can only be used in conjunction with a valid api token, access key and secret. More information can be found [here](https://golfbert.com/api).
 *
 * OpenAPI spec version: 1.0.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Courseteebox
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-16T22:14:27.256-07:00")
public class Courseteebox   {
  @SerializedName("courseid")
  private Integer courseid = null;

  @SerializedName("color")
  private String color = null;

  @SerializedName("slope")
  private Double slope = null;

  @SerializedName("rating")
  private Double rating = null;

  @SerializedName("teeboxtype")
  private String teeboxtype = null;

  public Courseteebox courseid(Integer courseid) {
    this.courseid = courseid;
    return this;
  }

   /**
   * Get courseid
   * @return courseid
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getCourseid() {
    return courseid;
  }

  public void setCourseid(Integer courseid) {
    this.courseid = courseid;
  }

  public Courseteebox color(String color) {
    this.color = color;
    return this;
  }

   /**
   * Get color
   * @return color
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public Courseteebox slope(Double slope) {
    this.slope = slope;
    return this;
  }

   /**
   * Get slope
   * @return slope
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getSlope() {
    return slope;
  }

  public void setSlope(Double slope) {
    this.slope = slope;
  }

  public Courseteebox rating(Double rating) {
    this.rating = rating;
    return this;
  }

   /**
   * Get rating
   * @return rating
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getRating() {
    return rating;
  }

  public void setRating(Double rating) {
    this.rating = rating;
  }

  public Courseteebox teeboxtype(String teeboxtype) {
    this.teeboxtype = teeboxtype;
    return this;
  }

   /**
   * Get teeboxtype
   * @return teeboxtype
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTeeboxtype() {
    return teeboxtype;
  }

  public void setTeeboxtype(String teeboxtype) {
    this.teeboxtype = teeboxtype;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Courseteebox courseteebox = (Courseteebox) o;
    return Objects.equals(this.courseid, courseteebox.courseid) &&
        Objects.equals(this.color, courseteebox.color) &&
        Objects.equals(this.slope, courseteebox.slope) &&
        Objects.equals(this.rating, courseteebox.rating) &&
        Objects.equals(this.teeboxtype, courseteebox.teeboxtype);
  }

  @Override
  public int hashCode() {
    return Objects.hash(courseid, color, slope, rating, teeboxtype);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Courseteebox {\n");
    
    sb.append("    courseid: ").append(toIndentedString(courseid)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    slope: ").append(toIndentedString(slope)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    teeboxtype: ").append(toIndentedString(teeboxtype)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

